# 参数配置
base:
  config:
    server:
      port: 3081
    redis:
      hostname: 127.0.0.1
      password:
      port: 6379
    mysql:
      hostname: 127.0.0.1:3306
      username: root
      password:
    oss:
      endpoint:
      access_key_id:
      access_key_secret:
      bucket_address:
      bucket_name:
    wechat:
      mini:
        app_id:
        app_secret:
        auth:

# 服务端口号
server:
  port: ${base.config.server.port}
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    max-connections: 10000

spring:
  application:
    # 应用名称
    name: api-ams

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL #不为空的属性才会序列化,具体属性可看JsonInclude.Include
    #    property-naming-strategy: SNAKE_CASE
    #    property-naming-strategy: SNAKE_CASE
    locale: zh
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true # 返回的java.util.date转换成timestamp
      FAIL_ON_EMPTY_BEANS: true # 对象为空时是否报错，默认true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      USE_GETTERS_AS_SETTERS: true
    parser:
      ALLOW_SINGLE_QUOTES: true

  # Redis 缓存配置
  redis:
    database: 1
    host: ${base.config.redis.hostname}
    port: ${base.config.redis.port}
    password: ${base.config.redis.password}
    timeout: 1s
    lettuce:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: 5000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）

  # 数据库连接池
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${base.config.mysql.hostname}/shopping_center_master?useAffectedRows=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${base.config.mysql.username}
    password: ${base.config.mysql.password}
    ##  Hikari 连接池配置 ------ 详细配置请访问：https://github.com/brettwooldridge/HikariCP
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 18000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池母子
      pool-name: MyHikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 180000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.ejzblog.pet.domain
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

oss:
  endpoint: ${base.config.oss.endpoint}
  access_key_id: ${base.config.oss.access_key_id}
  access_key_secret: ${base.config.oss.access_key_secret}
  bucket_address: ${base.config.oss.bucket_address}
  bucket_name: ${base.config.oss.bucket_name}

wechat:
  mini:
    app_id: ${base.config.wechat.mini.app_id}
    app_secret: ${base.config.wechat.mini.app_secret}
    auth: ${base.config.wechat.mini.auth}

# 日志
logging:
  config: classpath:logback-spring.xml
  debug:
    level:
      com.baomidou.mybatisplus.samples: debug
      org.springframework.boot.autoconfigure: error
      root: info
